services:
  postgres:
    image: postgres:15
    container_name: exam_mentor_db
    restart: always
    environment:
      POSTGRES_USER: exam_mentor
      POSTGRES_PASSWORD: exam_mentor
      POSTGRES_DB: exam_mentor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["/bin/sh", "-c", "mkdir -p /root/db && docker-entrypoint.sh postgres"]

  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/go-backend:latest"
    container_name: go-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://exam_mentor:exam_mentor@postgres:5432/exam_mentor?sslmode=disable"
    ports:
      - "4000:4000"
    restart: always

  question_forge:
    image: question_forge  # ✅ Using locally built image
    container_name: question_forge
    depends_on:
      - postgres
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5001:5000"
    restart: always

  model_service:
    image: model_service  # ✅ Using locally built image
    container_name: model_service
    depends_on:
      - go-backend
    ports:
      - "6000:6000"
      - "8000:8000"
    restart: always

  course_builder:
    image: course_builder  # ✅ Using locally built image
    container_name: course_builder
    depends_on:
      - go-backend
    ports:
      - "3000:80"
    restart: always

volumes:
  postgres_data:
