name: Build and Push Docker Images for Model Service and Backend

on:
  push:
    branches:
      - main  # Only run when pushing to the main branch
    paths:
      - 'model_service/**'  # Trigger for changes in model_service directory
      - 'backend/**'         # Trigger for changes in backend directory

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Or use a Docker Access Token

      # Step 4: Conditionally build and push the model service Docker image if model_service has changed
      - name: Build and push model service Docker image
        if: contains(github.event.head_commit.message, 'model_service')  # Only trigger if model_service changed
        working-directory: model_service
        run: |
          docker build -t chiramlittleton/model_service:latest .
          docker push chiramlittleton/model_service:latest

      # Step 5: Conditionally build and push the backend Docker image if backend has changed
      - name: Build and push backend Docker image
        if: contains(github.event.head_commit.message, 'backend')  # Only trigger if backend changed
        working-directory: backend
        run: |
          docker build -t chiramlittleton/backend:latest .
          docker push chiramlittleton/backend:latest
