name: Build and Push Docker Images

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        working-directory: backend  # Assuming backend is in the "backend" directory
        run: |
          docker build -t chiramlittleton/backend:latest .
          docker push chiramlittleton/backend:latest

  build-model-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Model Service Docker image
        working-directory: model_service  # Assuming model_service is in the "model_service" directory
        run: |
          docker build -t chiramlittleton/model_service:latest .
          docker push chiramlittleton/model_service:latest
